### ISSUE TITLE
What is this repo?

### ISSUE THREAD

**Issue by kubasienki** [db-ok/SofleChocWireless#1]
the readme doesn't explain the difference over sofle choc found in the official sofle repo. The explanation would help to grasp the difference at the first glance. 

Now I'm guessing it's just for the firmware? Or did the physical side also change?

**Comment by db-ok** [comment]
> the readme doesn't explain the difference over sofle choc found in the official sofle repo. The explanation would help to grasp the difference at the first glance.
> 
> Now I'm guessing it's just for the firmware? Or did the physical side also change?

This is a new physical design with features specifically designed for wireless boards. The repo is not finished yet, though, but keep an eye out, it will be updated soon with the details you're asking about.
