### ISSUE TITLE
Help: Where did you buy the keycaps.

### ISSUE THREAD

**Issue by antiquerefer** [db-ok/SofleChocWireless#11]
**Kind of issue?**
Assembly

**What steps have you taken**
* [X] I have searched the Issues page
* [X] I have read the documentation 
* [X] For LED issues I have checked the following things 
        - the microcontroller is programmed (and currently telling the LEDs to do something)
        - the microcontroller is powered (and showing LEDs)
        - the LEDs are powered (check voltage with multimeter)
        - are any of the LEDs showing 

**What is the issue?**
@db-ok The keycaps you're using look great and seem customized. I'm wondering where you bought them. I’ve noticed that choco keycaps are hard to find.

**Comment by db-ok** [comment]
The non-shine-through keycaps in the first photo are the MBK Legend keyset. I got mine from littlekeyboards.com . The shine-through ones in the other photos are a Kailh brand choc keyset. I'm not sure if this set is still sold anymore, though. There are also some keysets called THT (Tai Hao Thins) that fit choc keycaps (make sure to pick the choc option as the THT sets come in both MX and Choc varieties). They seem like a good option, but I haven't tried them yet myself.
