### ISSUE TITLE
Status update

### ISSUE THREAD

**Issue by tpstevens** [db-ok/SofleChocWireless#2]
**What feature would you like to see?**

Hello! Was looking around for wireless split keyboards, found your repo, and noted that it's still in prototype state. Have there been any issues that you've found, or is it ready for wider consumption? I'm happy to tinker with it knowing that there may be issues that need worked around, just curious if there was anything pending or if I should give it a shot. Thanks!

**Are you prepared to help?** 
_Bare in mind that we are also hobbiests, and built boards to our own requirements._ 
_We are currently using them without issue, so development is going to be slow, and only where we can see benefit, or are already making compatible changes. The quickest way to get the features you want is to do them yourself._

yes!

**Comment by db-ok** [comment]
I use this board without issues. I would suggest if you are interested in building it, go right ahead!

**Comment by db-ok** [comment]
This board is a DIY project, and it comes with no guarantees, but I use it, and it works to my satisfaction with no functional issues that I know of
