### ISSUE TITLE
Can I use kailh/mx style switches and sockets?

### ISSUE THREAD

**Issue by backtrackjack** [db-ok/SofleChocWireless#5]
I'm currently building a sofle rgb, but really like the look of this model and can see myself migrating to wireless eventually and am thinking about what parts I can re-use. I'm not that sadistic enough to de-solder everything to attach to this but would be cool to move the switches at least over (kailh speed silver)

**Comment by db-ok** [comment]
This keyboard only supports Kailh Choc v1 switches -- it will not work with any MX-style switches. However, it is possible to convert your Sofle RGB board to be wireless with some modifications, although if you want to use the RGB lighting, battery life will be a concern.
